# Generated by Django 5.0.6 on 2026-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_side',
            field=models.CharField(blank=True, choices=[('left', 'Левая'), ('right', 'Правая')], max_length=10, null=True, verbose_name='Предпочтительная сторона'),
        ),
    ]
