# Generated by Django 5.0.6 on 2026-03-12 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_format'),
        ('users', '0002_userprofile_preferred_side'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('tournament_win', 'Победа в турнире'), ('tournament_place', 'Призовое место в турнире'), ('rating_milestone', 'Достижение рейтинга'), ('games_milestone', 'Количество игр')], max_length=30, verbose_name='Тип достижения')),
                ('position', models.IntegerField(blank=True, help_text='Позиция в турнире (1, 2, 3, и т.д.)', null=True, verbose_name='Место')),
                ('date_achieved', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация: название турнира, рейтинг, и т.д.', verbose_name='Метаданные')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Достижение игрока',
                'verbose_name_plural': 'Достижения игроков',
                'ordering': ['-date_achieved'],
                'indexes': [models.Index(fields=['user', '-date_achieved'], name='users_playe_user_id_969d7e_idx'), models.Index(fields=['achievement_type', 'date_achieved'], name='users_playe_achieve_f4e263_idx')],
            },
        ),
    ]
