# Generated by Django 5.0.6 on 2026-01-29 09:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_booking_required_rating_levels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('registration_deadline', models.DateTimeField(verbose_name='Дедлайн регистрации')),
                ('max_participants', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(128)], verbose_name='Макс. участников')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Взнос за участие')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Призовой фонд')),
                ('format', models.CharField(choices=[('single_elimination', 'Олимпийская система'), ('double_elimination', 'Двойная олимпийская'), ('round_robin', 'Круговая система')], default='single_elimination', max_length=20, verbose_name='Формат турнира')),
                ('min_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Минимальный рейтинг')),
                ('max_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Максимальный рейтинг')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('registration_open', 'Регистрация открыта'), ('registration_closed', 'Регистрация закрыта'), ('in_progress', 'Идет турнир'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournaments/', verbose_name='Постер турнира')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(verbose_name='Раунд')),
                ('match_number', models.IntegerField(verbose_name='Номер матча')),
                ('score', models.JSONField(blank=True, default=dict, help_text='{"sets": ["6-4", "7-5"], "games": "13-9"}', verbose_name='Счет')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Дата матча')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Время матча')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('in_progress', 'Идет'), ('completed', 'Завершен'), ('walkover', 'Walkover'), ('cancelled', 'Отменен')], db_index=True, default='scheduled', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.court', verbose_name='Корт')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournament.tournamentmatch', verbose_name='Следующий матч')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_p1', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 1')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches_as_p2', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament', verbose_name='Турнир')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_won_matches', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Матч турнира',
                'verbose_name_plural': 'Матчи турнира',
                'ordering': ['round', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(blank=True, help_text='Номер посева (1 - сильнейший)', null=True, verbose_name='Посев')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('refunded', 'Возвращено')], db_index=True, default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('final_position', models.IntegerField(blank=True, null=True, verbose_name='Итоговое место')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournament.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турнира',
                'ordering': ['seed', 'registered_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Номер раунда')),
                ('name', models.CharField(help_text='Например: 1/8 финала, 1/4 финала, Полуфинал, Финал', max_length=100, verbose_name='Название раунда')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала раунда')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournament.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Раунд турнира',
                'verbose_name_plural': 'Раунды турнира',
                'ordering': ['round_number'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'start_date'], name='tournament__status_ac681e_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['registration_deadline'], name='tournament__registr_afe8ae_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['tournament', 'round'], name='tournament__tournam_ae1761_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['status', 'scheduled_date'], name='tournament__status_f7fa44_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'payment_status'], name='tournament__tournam_ab9ec2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentround',
            unique_together={('tournament', 'round_number')},
        ),
    ]
