# Generated by Django 5.0.6 on 2026-02-02 19:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadelTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Например: "Los Campeones" (для постоянных пар)', max_length=200, verbose_name='Название пары')),
                ('seed', models.IntegerField(blank=True, null=True, verbose_name='Посев')),
                ('is_temporary', models.BooleanField(default=False, help_text='True для Americano/Mexicano (пара на 1 раунд)', verbose_name='Временная пара')),
                ('round_number', models.IntegerField(blank=True, help_text='В каком раунде эта временная пара играет', null=True, verbose_name='Номер раунда')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Padel пара',
                'verbose_name_plural': 'Padel пары',
                'ordering': ['tournament', 'seed', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='tournamentparticipant',
            options={'ordering': ['-total_points', '-matches_won', 'registered_at'], 'verbose_name': 'Участник турнира', 'verbose_name_plural': 'Участники турнира'},
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='score',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner',
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_mixed',
            field=models.BooleanField(default=False, help_text='True = обязательно мужчина+женщина в паре', verbose_name='Смешанный формат'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_team_tournament',
            field=models.BooleanField(default=False, help_text='True = постоянные пары, False = индивидуальный зачет с ротацией', verbose_name='Командный турнир'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='points_per_match',
            field=models.IntegerField(choices=[(16, '16 очков за матч'), (20, '20 очков за матч'), (24, '24 очка за матч'), (32, '32 очка за матч')], default=24, help_text='До скольки очков играется матч (для Americano/Mexicano)', verbose_name='Очков за матч'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='detailed_score',
            field=models.JSONField(blank=True, default=dict, help_text='{"sets": [{"team1": 6, "team2": 4}]} - если играли по сетам', verbose_name='Детальный счет'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='score_team1',
            field=models.IntegerField(default=0, verbose_name='Очки пары 1'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='score_team2',
            field=models.IntegerField(default=0, verbose_name='Очки пары 2'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='current_rank',
            field=models.IntegerField(blank=True, help_text='Позиция после последнего раунда (для Mexicano)', null=True, verbose_name='Текущая позиция'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='matches_lost',
            field=models.IntegerField(default=0, verbose_name='Матчей проиграно'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='matches_played',
            field=models.IntegerField(default=0, verbose_name='Матчей сыграно'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='matches_won',
            field=models.IntegerField(default=0, verbose_name='Матчей выиграно'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Используется для Team форматов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_in_tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Постоянный партнер'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='team_name',
            field=models.CharField(blank=True, help_text='Для Team форматов', max_length=200, verbose_name='Название пары'),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='total_points',
            field=models.IntegerField(default=0, help_text='Сумма очков за все раунды (для Americano/Mexicano)', verbose_name='Всего очков'),
        ),
        migrations.AddField(
            model_name='tournamentround',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Раунд завершен'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('americano', 'Americano - Индивидуальный зачет, ротация партнеров'), ('mexicano', 'Mexicano - Индивидуальный зачет, пары по рейтингу'), ('mixed_americano', 'Mixed Americano - Обязательно мужчина+женщина'), ('team_americano', 'Team Americano - Постоянные пары, все со всеми'), ('team_mexicano', 'Team Mexicano - Постоянные пары, пары по рейтингу'), ('doubles_elimination', 'Doubles Elimination - Олимпийская система (пары)'), ('doubles_round_robin', 'Doubles Round Robin - Круговая система (пары)')], default='americano', max_length=30, verbose_name='Формат турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(help_text='Для Americano лучше кратно 4', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(128)], verbose_name='Макс. участников'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='seed',
            field=models.IntegerField(blank=True, help_text='Номер посева для пары (1 - сильнейшая)', null=True, verbose_name='Посев пары'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='name',
            field=models.CharField(help_text='Раунд 1, 1/4 финала, Полуфинал, Финал и т.д.', max_length=100, verbose_name='Название раунда'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['format'], name='tournament__format_2d92c9_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', '-total_points'], name='tournament__tournam_44c089_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentparticipant',
            index=models.Index(fields=['tournament', 'current_rank'], name='tournament__tournam_30c137_idx'),
        ),
        migrations.AddField(
            model_name='padelteam',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padel_teams_as_p1', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 1'),
        ),
        migrations.AddField(
            model_name='padelteam',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padel_teams_as_p2', to=settings.AUTH_USER_MODEL, verbose_name='Игрок 2'),
        ),
        migrations.AddField(
            model_name='padelteam',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament', verbose_name='Турнир'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournament.padelteam', verbose_name='Пара 1'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournament.padelteam', verbose_name='Пара 2'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winning_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournament.padelteam', verbose_name='Победившая пара'),
        ),
        migrations.AddIndex(
            model_name='padelteam',
            index=models.Index(fields=['tournament', 'is_temporary'], name='tournament__tournam_5f3983_idx'),
        ),
        migrations.AddIndex(
            model_name='padelteam',
            index=models.Index(fields=['tournament', 'round_number'], name='tournament__tournam_b90970_idx'),
        ),
    ]
