# Generated by Django 5.0.6 on 2026-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_padelteam_alter_tournamentparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('americano', 'Round-Robin - Каждый с каждым, пары постоянно меняются')], default='americano', max_length=30, verbose_name='Формат турнира'),
        ),
    ]
