# Generated by Django 5.0.6 on 2026-02-05 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_required_rating_levels_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_round',
            field=models.IntegerField(default=0, help_text='Номер текущего раунда (0 = игра не началась)', verbose_name='Текущий раунд'),
        ),
        migrations.AddField(
            model_name='booking',
            name='game_mode',
            field=models.CharField(choices=[('regular', 'Обычная игра'), ('americano', 'Americano - Меняющиеся пары'), ('mexicano', 'Mexicano - Пары по рейтингу'), ('training', 'Тренировка')], db_index=True, default='regular', max_length=20, verbose_name='Режим игры'),
        ),
        migrations.AddField(
            model_name='booking',
            name='game_status',
            field=models.CharField(choices=[('pending', 'Ожидает игроков'), ('ready', 'Готова к началу'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=20, verbose_name='Статус игры'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Игра видна другим пользователям во вкладке "Игры"', verbose_name='Публичная игра'),
        ),
        migrations.AddField(
            model_name='booking',
            name='max_rating_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальный рейтинг для участия', max_digits=3, null=True, verbose_name='Максимальный рейтинг'),
        ),
        migrations.AddField(
            model_name='booking',
            name='min_rating_required',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальный рейтинг для участия', max_digits=3, null=True, verbose_name='Минимальный рейтинг'),
        ),
        migrations.AddField(
            model_name='booking',
            name='points_per_round',
            field=models.IntegerField(default=24, help_text='Количество очков для игры до окончания раунда', verbose_name='Очков в раунде'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rounds_count',
            field=models.IntegerField(default=3, help_text='Для Americano/Mexicano режимов', verbose_name='Количество раундов'),
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Порядковый номер участника (1-4)', verbose_name='Позиция')),
                ('status', models.CharField(choices=[('invited', 'Приглашен'), ('accepted', 'Принял'), ('declined', 'Отклонил'), ('joined', 'Присоединился'), ('left', 'Покинул')], db_index=True, default='invited', max_length=20, verbose_name='Статус')),
                ('total_points', models.IntegerField(default=0, help_text='Сумма очков за все раунды', verbose_name='Всего очков')),
                ('rating_before', models.DecimalField(decimal_places=2, help_text='Рейтинг игрока перед началом игры', max_digits=3, verbose_name='Рейтинг до игры')),
                ('rating_change', models.DecimalField(decimal_places=2, default=0, help_text='Изменение рейтинга после игры (может быть отрицательным)', max_digits=4, verbose_name='Изменение рейтинга')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participants', to='booking.booking', verbose_name='Бронирование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник игры',
                'verbose_name_plural': 'Участники игр',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['booking', 'status'], name='booking_gam_booking_e305b1_idx'), models.Index(fields=['user', 'status'], name='booking_gam_user_id_11072c_idx')],
                'unique_together': {('booking', 'position'), ('booking', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Номер раунда (1, 2, 3, ...)', verbose_name='Номер раунда')),
                ('team1_score', models.IntegerField(default=0, verbose_name='Счет команды 1')),
                ('team2_score', models.IntegerField(default=0, verbose_name='Счет команды 2')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rounds', to='booking.booking', verbose_name='Бронирование')),
                ('team1_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_team1_player1', to=settings.AUTH_USER_MODEL, verbose_name='Команда 1 - Игрок 1')),
                ('team1_player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_team1_player2', to=settings.AUTH_USER_MODEL, verbose_name='Команда 1 - Игрок 2')),
                ('team2_player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_team2_player1', to=settings.AUTH_USER_MODEL, verbose_name='Команда 2 - Игрок 1')),
                ('team2_player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_team2_player2', to=settings.AUTH_USER_MODEL, verbose_name='Команда 2 - Игрок 2')),
            ],
            options={
                'verbose_name': 'Раунд игры',
                'verbose_name_plural': 'Раунды игр',
                'ordering': ['round_number'],
                'indexes': [models.Index(fields=['booking', 'round_number'], name='booking_gam_booking_8af3fb_idx'), models.Index(fields=['booking', 'is_completed'], name='booking_gam_booking_fcacde_idx')],
                'unique_together': {('booking', 'round_number')},
            },
        ),
    ]
