# Generated by Django 5.0.6 on 2026-02-26 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_current_round_booking_game_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки')),
                ('is_system_message', models.BooleanField(default=False, help_text='Автоматическое сообщение от системы (например, "Игрок присоединился")', verbose_name='Системное сообщение')),
                ('is_read', models.BooleanField(default=False, help_text='Помечено как прочитанное всеми участниками', verbose_name='Прочитано')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='booking.booking', verbose_name='Бронирование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение в чате',
                'verbose_name_plural': 'Сообщения в чате',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='booking_gam_booking_927878_idx'), models.Index(fields=['user', 'created_at'], name='booking_gam_user_id_65fa02_idx'), models.Index(fields=['booking', 'is_read'], name='booking_gam_booking_601290_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, help_text='Сообщение от игрока при запросе на присоединение', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='booking.booking', verbose_name='Бронирование')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_list_responses', to=settings.AUTH_USER_MODEL, verbose_name='Кто ответил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на присоединение',
                'verbose_name_plural': 'Запросы на присоединение',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'status'], name='booking_wai_booking_b171ca_idx'), models.Index(fields=['user', 'status'], name='booking_wai_user_id_62e0eb_idx'), models.Index(fields=['created_at'], name='booking_wai_created_3071eb_idx')],
                'unique_together': {('booking', 'user')},
            },
        ),
    ]
