# Generated by Django 5.0.6 on 2026-03-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_gamechat_waitinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='game_mode',
            field=models.CharField(choices=[('regular', 'Обычная игра'), ('americano', 'Round-Robin - Каждый с каждым, пары меняются'), ('training', 'Тренировка')], db_index=True, default='regular', max_length=20, verbose_name='Режим игры'),
        ),
    ]
