# Generated by Django 5.0.6 on 2026-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_game_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='game_mode',
            field=models.CharField(choices=[('regular', 'Обычная игра'), ('americano', 'Americano - Каждый с каждым, пары меняются'), ('mexicano', 'Mexicano - Пары по рейтингу'), ('training', 'Тренировка')], db_index=True, default='regular', max_length=20, verbose_name='Режим игры'),
        ),
    ]
